- name: Install database server
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ wikidb_packages }}"

- name: Install database server config
  template:
    src: my.cnf.j2
    dest: "{{ wikidb_mysql_conf_file }}"

- name: Ensure database server is running
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Add database for each wiki
  tags: db
  mysql_db:
    name: "{{ item.value.db.database }}"
    state: present
  with_dict: "{{ mediawikis }}"

- name: Add database user for the wiki
  mysql_user:
    name: "{{ item.value.db.user }}"
    password: "{{ item.value.db.password }}"
    priv: "*.*:ALL"
    host: "{{ item.value.db.server_client }}"
    state: present
  with_dict: "{{ mediawikis }}"
