- name: Install database server
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
  tags: db

- name: Install sql config
  copy: src=my.cnf dest=/etc/my.cnf.d/custom.cnf
  tags: db

- name: Ensure sql is running
  service: name=mariadb state=started enabled=yes
  tags: db
