- name: Install database server
  package:
    name: mariadb-server
    state: present

- name: Install database server config
  template:
    src: my.cnf.j2
    dest: "{{ wikidb_mysql_conf_dir }}/custom.cnf"

- name: Ensure database server is running
  service:
    name: mariadb
    state: started
    enabled: yes
