---
# tasks file for tsv-tools

- name: Setup directories
  become: no
  file:
    path: "{{ item }}"
    mode: 0777
    recurse: yes
    state: directory
  loop:
    -  "{{ src_root }}"
    -  "{{ install_dir }}/bin/"

- name: Get docker files to local host
  command:
    cmd: docker pull "{{ container }}"
  become: yes
  delegate_to: localhost
  when: false #skip for now

- name: Copy scripts
  get_url:
    url: "{{ github_src }}/{{ item.name }}"
    dest: "{{ install_dir }}/bin/{{ item.install_as }}"
    mode: 0755
  loop: "{{ asr_scripts }}"


- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX"
    recurse: yes
  when: shared_group is defined
