---
# tasks file for check-hfst

- name: compile_root directory exists with 0777 permission
  become: no
  file: path={{ compile_root }}
    mode=0777
    recurse=no
    state=directory

- name: Download and extract tarball
  unarchive:
    src={{ release_url }}/{{ tarball }}
    dest={{ compile_root }}
    creates={{ compile_dir }}
    remote_src=yes

# TODO: Make tests run against compile dir, not assume them to be installed and default (with next HFST update) -- mma 20.2.2017
- name: Run tests
  command: "{{ item }} > {{ item }}.LOG"
  args:
    chdir: "{{ compile_dir }}"
  environment:
    PATH: "{{ install_prefix }}/ling/hfst/{{ hfst_version }}/bin:{{ install_prefix }}/ling/hfstospell/{{ hfst_ospell_version }}/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ install_prefix }}/ling/hfst/{{ hfst_version }}/lib:{{ install_prefix }}/ling/hfstospell/{{ hfst_ospell_version }}/lib"
  with_items:
#   - ./check-morphologies.sh
   - ./check-tools.sh
#   - ./check-ospell.sh
  ignore_errors: yes