---
# defaults

package_name: hunpos
version: "{{ hunpos_version }}"
zipfilename: "hunpos-{{ hunpos_version }}-32bit-linux-lib.zip"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"
lib_dir: "{{ install_dir }}/lib"
