- name: Install packages required for wiki setup
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mediawiki_packages }}"

- name: Install oregano
  get_url:
    url: https://raw.githubusercontent.com/wikimedia/translatewiki/340394a9eb459e5477f98da6ed82d9cc156f79c5/bin/oregano
    dest: /srv/mediawiki/oregano
    checksum: sha1:a6a9028352d72b45cd1dc07113ea659ff0d4cd57
    mode: a+x

# So far only nimiarkisto is supported
- name: Install monthly dump script
  copy:
    src: dump_nimiarkisto
    dest: /etc/cron.monthly/
    mode: 0755

- name: Configure all wiki instances
  include: instance.yml
  with_dict: "{{ mediawikis }}"
  loop_control:
    loop_var: instance
