---
# defaults file for kaldi

# Check http://kaldi-asr.org/doc/versions.html
release_url: https://github.com/kaldi-asr/kaldi.git
install_dir: "{{ install_prefix }}/ling/kaldi/{{ kaldi_version.number }}"