---
# defaults file for kaldi

# Check http://kaldi-asr.org/doc/versions.html
release_url: https://github.com/kaldi-asr/kaldi.git
install_dir: "{{ install_prefix }}/ling/kaldi/{{ kaldi_version.number }}"
# use intel here
compiler_call: ". /appl/profile/zz-csc-env.sh && module load intel/19.0.4 && module load intel-mkl/2019.0.4-omp &&"
make_extra_flags: "-j 30"