---
# tasks file for praat
- name: "Debian/Ubuntu: Install list of packages"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
       - none
  when:
    - ansible_os_family == "Debian"
    - is_admin

- name: "RHEL/CentOS: Install list of packages"
  yum: 
    name: " {{item}} "
    state: present
  become: yes
  with_items:
       - none
  when:
    - ansible_os_family == "RedHat"
    - is_admin

- name: src_root directory exists with 0777 permission
  become: no
  file:
    path: "{{ src_root }}"
    mode: 0777
    recurse: yes
    state: directory

- name: Get source
  unarchive:
    src: "{{ release_url }}"
    dest: "{{ src_root }}"
    remote_src: yes

- name: Running make 
  shell: bash --login -c "make -j8 > MAKE.log"
  args:
    chdir: "{{ compile_dir }}"
    #creates: MAKE.log

- name: create install_dir subtree
  become: no
  file:
    path: "{{ install_dir }}/{{ item }}"
    mode: 0775
    recurse: no
    state: directory
  with_items:
    - bin

- name: Copy udpipe to install_dir
  copy:
    remote_src: true
    src: "{{ compile_dir }}/udpipe"
    dest: "{{ install_dir }}/bin/udpipe"
    mode: 0755

- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX"
    recurse: yes
  when: shared_group is defined