---
# The Language Bank of Finland Software Stack on CSC's Taito-cluster
#

- hosts: taito
  vars:
   - hfst_version: 3.15.0
   - hfst_ospell_version: 0.5.1
   - finnish_parse_version: 1.0
   - praat_version: 6.0.29
   - nasm_version: 2.13.02
   - finnish_tagtools_version: 1.1
   - kaldi_version:
      number: 5.2.5
      githash: 3e57783
#  - ffmpeg_version: see roles/ffmpeg/defaults/main.yml
      

  become: no
  roles:
   - { role: hfst, tags: hfst }
   - { role: hfst-morphologies, tags: hfst-morphologies }
   - { role: hfst-ospell, tags: hfst-ospell }
   - { role: check-hfst, tags: check-hfst }
   - { role: finnish-parse, branch: master, tags: finnish-parse }
   - { role: praat, branch: master, tags: praat }
   - { role: nasm, tags: nasm }
   - { role: ffmpeg, branch: master, tags: ffmpeg }
   - { role: finnish-tagtools, tags: finnish-tagtools }
   - { role: kaldi, tags: kaldi }



     
