---
# The Language Bank of Finland Software Stack on CSC's Taito-cluster
#

- hosts: puhti
  vars:
   - hfst_version: 3.15.0
   - hfst_ospell_version: 0.5.1
   - finnish_parse_version: 1.0
   - praat_version: 6.0.43
   - nasm_version: 2.14.02
   - finnish_tagtools_version: 1.4.0
   - kaldi_version:
      number: 5.2.86
      githash: 53e5e12
   - hunpos_version: 1.0
   - sparv_pipeline_version: 2.0_MIT_2017-10-23
#  - ffmpeg_version: see roles/ffmpeg/defaults/main.yml
#  - cstlemma_version: see roles/cstlemma/defaults/main.yml
   - udpipe_version: 1.2.0
      

  become: no
  gather_facts: true
  gather_subset: min
  roles:
   - { role: hfst, tags: hfst }
   - { role: hfst-morphologies, tags: hfst-morphologies }
   - { role: hfst-ospell, tags: hfst-ospell }
   - { role: check-hfst, tags: check-hfst }
   - { role: finnish-parse, branch: master, tags: finnish-parse }
   - { role: praat, tags: praat }
   - { role: nasm, tags: nasm }
   - { role: ffmpeg, branch: master, tags: ffmpeg }
   - { role: finnish-tagtools, tags: finnish-tagtools }
   - { role: kaldi, tags: kaldi }
   - { role: udpipe, tags: udpipe }
   - { role: hunpos, tags: hunpos }
   - { role: sparv_pipeline, tags: sparv_pipeline }
   - { role: cstlemma, tags: cstlemma }



     
