---
# Install PIP modules

- name: Install PIP3 modules
  become: "{{ is_admin }}"
  pip:
    executable: "{{ item[0] }}"
    name: "{{ item[1] }}"
  loop: "{{ query('nested', pip_variants, pip_modules ) }}"


