- name: Add repository for hhvm
  yum_repository:
    name: hhvm-repo
    description: Copr repo for hhvm-repo owned by no1youknowz
    baseurl: https://copr-be.cloud.fedoraproject.org/results/no1youknowz/hhvm-repo/epel-7-$basearch/
    skip_if_unavailable: yes
    gpgcheck: yes
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/no1youknowz/hhvm-repo/pubkey.gpg
    repo_gpgcheck: no
    enabled: yes

- name: Install hhvm
  yum: name=hhvm state=present

- name: Install hhvm systemd init file
  copy: src=hhvm.service dest=/etc/systemd/system/hhvm.service mode=0644

- name: Install configuration file 1
  template: src=server.ini.j2 dest=/etc/hhvm/server.ini mode=0644

- name: Install configuration file 2
  copy: src=php.ini dest=/etc/hhvm/php.ini mode=0644

- name: Run hhvm
  service: name=hhvm state=started enabled=yes

- name: Create log dir
  file: path=/www/{{ webdomain }}/logs/ state=directory owner=hhvm mode=0644

- name: Create log file
  copy: dest=/www/{{ webdomain }}/logs/error_php owner=hhvm mode=0644 content="" force=no

- name: Symlink hhvm as php
  file: src=/usr/bin/hhvm dest=/usr/bin/php state=link
