- name: Install packages from yum
  yum: name={{ item }} state=present
  with_items:
  - python-pip
  - python-setuptools
  - httpd-devel
  - python-devel.x86_64
  - gcc
  - php-pear
  - php-devel
  - php-mongodb
  - openssl-devel.x86_64
  - mod_wsgi

- name: Install python dependencies using pip
  pip: name={{ item.name }} version={{ item.version | default(omit) }}  state=present
  with_items:
    - name: django
      version: 1.9
    - name: pymongo
    - name: requests
    - name: PyExecJS
    - name: hfst

- name: Add mongodb repo
  copy:
    src: mongodb-org-3.2.repo
    dest: /etc/yum.repos.d/mongodb-org-3.2.repo

- name: Install mongodb
  yum: name=mongodb-org

- name: Start mongodb
  service: name=mongod state=started enabled=yes

- name: Set SELinux to permissive mode (required by mongodb)
  selinux: policy=targeted state=permissive

- name: Install php dependencies
  pear:
    name: pecl/mongodb
    state: present

- name: Install JavaScript interpret
  yum:
    name: nodejs
    state: present
    disablerepo: hhvm-repo

- name: Create smsxml directory
  file: path=/www/smsxml state=directory

- name: Download smsxml
  get_url: url=http://mikakalevi.com/downloads/sms_xml.zip dest=/www/smsxml/sms_xml.zip force=yes

- name: Extract smsxml
  unarchive: src=/www/smsxml/sms_xml.zip dest=/www/smsxml/ copy=no

- name: Make update script executable
  file: path=/www/smsxml/update_smsxml.sh mode="u=rwx"

- name: symlink update script
  file: src=/www/smsxml/update_smsxml.sh dest=/bin/update_smsxml state=link force=yes

- name: Download smsxml mediawiki extension
  get_url: url=http://mikakalevi.com/downloads/sms_xml_wiki_extensions.zip dest=/www/smsxml/sms_xml_wiki_extensions.zip force=yes

- name: Create smsxml mediawiki extension directory
  file: path=/www/smsxml/wiki state=directory

- name: Extract smsxml mediawiki extension
  unarchive: src=/www/smsxml/sms_xml_wiki_extensions.zip dest=/www/smsxml/wiki/ copy=no

- name: Copy smsxml configuration
  template: src=settings.py dest=/www/smsxml/saame/settings.py

- name: Copy smsxml apache configuration
  template: src=smsxml.conf dest=/etc/httpd/conf.d/smsxml.conf

- name: Create xml directory
  file: path=/www/smsxml/xmls state=directory

- name: Setup git for SMS files
  git:
    repo: https://github.com/mikahama/saame_testi.git
    dest: /www/smsxml/xmls/sms
    clone: yes
    accept_hostkey: yes


- name: Setup git for IHZ files
  git:
    repo: https://github.com/mikahama/inkeroinen.git
    dest: /www/smsxml/xmls/izh
    clone: yes
    accept_hostkey: yes

- name: Copy mod_uwsgi sources
  copy: src=mod_uwsgi.c dest=/www/smsxml/mod_uwsgi.c

- name: Build mod_uwsgi
  command: apxs -c -i mod_uwsgi.c
  args:
    chdir: /www/smsxml/
    creates: /usr/lib64/httpd/modules/mod_uwsgi.so

- name: Copy mediawiki user script
  template: src=add_wikiuser.sh dest=/www/smsxml/add_wikiuser.sh mode="u=rwx"

- name: Add mediawiki user for smsxml
  command: /www/smsxml/add_wikiuser.sh
  args:
    creates: /srv/mediawiki/workdir/maintenance/smsxml_user_added
  become: true

- name: Copy migrate script
  template: src=migrate.sh dest=/www/smsxml/migrate.sh mode="u=rwx"

- name: Make django migrations
  command: /www/smsxml/migrate.sh
  become: true

- name: Create symlink to MediaWiki code
  file: src=/www/smsxml/wiki/extensions/Saame dest=/www/{{webdomain}}/docroot/w/extensions/Saame state=link force=yes

- name: Copy smsxml wiki configuration
  template: src=SaameConfig.ini dest=/www/smsxml/wiki/extensions/Saame/SaameConfig.ini

