---
# defaults

package_name: check-hfst
release_url: http://hfst.github.io/downloads/
version: "{{ hfst_version }}"
tarball: "{{ package_name }}-{{ version }}.tar.gz"
compile_dir: "{{ compile_root }}/{{ package_name }}-{{ version }}"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"