---
# install dependencies

- apt: update_cache=yes cache_valid_time=3600
  become: yes
  when: is_admin

- name: install dependencies
  become: yes
  apt:
    name:
      - git-core
      - autoconf 
      - automake 
      - build-essential 
      - libass-dev 
      - libgpac-dev
      - libtheora-dev 
      - libtool 
      - libvorbis-dev
      - libnuma-dev
      - pkg-config 
      - texi2html 
      - zlib1g-dev
      - libmp3lame-dev
      - libssl-dev
      - mercurial
      - cmake 
      - cmake-curses-gui
      - libssl-dev
      - yasm
    state: present
  when: is_admin
    
