---

- name: create compile dir
  file:
    path: "{{ ffmpeg_source_dir }}"
    state: directory

- debug: var=ffmpeg_features
- import_tasks: dependencies.yml

- import_tasks: mp3lame.yml
  when: ffmpeg_mp3lame

- import_tasks: x265.yml
  when: ffmpeg_x265
  
- import_tasks: rtmp.yml
  when: ffmpeg_rtmp
  
- import_tasks: fdk-aac.yml
  when: ffmpeg_fdkaac
  
- import_tasks: x264.yml
  when: ffmpeg_x264
  
- import_tasks: opus.yml
  when: ffmpeg_opus
  
- import_tasks: vpx.yml
  when: ffmpeg_vpx

  
- import_tasks: ffmpeg.yml

    
- import_tasks: cleanup.yml
  when: ffmpeg_cleanup