---
- name: clone latest opus
  git: repo=https://git.xiph.org/opus.git
       dest={{ ffmpeg_source_dir }}/opus
       accept_hostkey=yes
       version={{ ffmpeg_opus_version }}
       
- name: compile libopus
  command: "{{ item }}" 
  args:
    chdir: "{{ ffmpeg_source_dir }}/opus" 
    creates: "{{ build_dir }}/lib/libopus.a"
  with_items:
    - ./autogen.sh
    - ./configure --disable-shared --prefix="{{ build_dir }}"
    - make {{ ffmpeg_cpu_flag }}
    - make install
    - make distclean       