- name: clone latest x264
  git: repo=https://code.videolan.org/videolan/x264.git
       dest={{ ffmpeg_source_dir }}/x264
       accept_hostkey=yes
       version={{ ffmpeg_x264_version }}

- name: Set nasm module call
  set_fact:
    nasm_modcall: "{{ 'module load nasm &&' if env_csc_hpc is defined else '' }}"

- name: compile x264
  shell: "{{ item }}" 
  args:
    chdir: "{{ ffmpeg_source_dir }}/x264" 
    #creates: "{{ ffmpeg_bin_dir }}/x264"
  with_items:
    - "{{ nasm_modcall }} ./configure --prefix={{ build_dir }} --enable-static"
    - "{{ nasm_modcall }} make {{ ffmpeg_cpu_flag }}"
    - make install
    - make distclean
