
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tagtools_install_dir }}"
    - "{{ tagtools_install_dir }}/bin"
    - "{{ compile_root }}"
    
- name: Unpack from tar
  unarchive:
    src: "{{ tagtools_tar}}"
    dest: "{{ compile_root }}"
    remote_src: yes

- name: Run make install
  make:
    chdir: "{{ compile_dir }}"
    target: install
    params:
      prefix: "{{ tagtools_install_dir }}"

- name: Fix permissions (if shared group is set)
  file:
    path="{{ tagtools_install_dir }}/.."
    group={{ shared_group }}
    mode="g+rwX,o+rX"
    recurse=yes
  when: shared_group is defined
