---
# install dependencies

- apt: update_cache=yes cache_valid_time=3600
  when: is_admin

- name: install dependencies
  action: apt pkg={{ item }} state=present
  with_items:
    - git-core
    - autoconf 
    - automake 
    - build-essential 
    - libass-dev 
    - libgpac-dev
    - libtheora-dev 
    - libtool 
    - libvorbis-dev 
    - pkg-config 
    - texi2html 
    - zlib1g-dev
    - libmp3lame-dev
    - libssl-dev
    - mercurial
    - cmake 
    - cmake-curses-gui
    - libssl-dev
  when: is_admin
    
