---

- name: get mp3lame
  unarchive:
    remote_src: yes
    validate_certs: no
    src: "https://sourceforge.net/projects/lame/files/lame/{{ ffmpeg_mp3lame_version }}/lame-{{ ffmpeg_mp3lame_version }}.tar.gz"
    dest: "{{ ffmpeg_source_dir }}"

- name: compile mp3lame
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/lame-{{ ffmpeg_mp3lame_version }}" 
  with_items:
    - ./configure --prefix={{ build_dir }} --disable-shared --enable-nasm --disable-frontend
    - make -j5
    - make install
