---
# tasks file for hfst

- name: "Debian/Ubuntu: Install list of packages"
  apt:
    name:
      - libreadline-dev
      - libtool
      - automake
      - flex
      - build-essential
      - swig
      - python3-dev
    state: present
  become: yes
  when:
    - ansible_os_family == "Debian"
    - is_admin

- name: "RHEL/CentOS: Install list of packages"
  yum: 
    name:
      - libreadline-dev
      - libtool
      - automake
      - flex
      - build-essential
      - swig
      - python3-dev
    state: present
  become: yes
  when:
    - ansible_os_family == "RedHat"
    - is_admin

- name: Ensure finnish locale
  become: yes
  locale_gen:
    name: fi_FI.UTF-8
    state: present
  when: is_admin

- name: compile_dir directory exists with 0777 permission
  become: no
  file:
    path: "{{ compile_dir }}"
    mode: 0777
    recurse: no
    state: directory

- name: check for install root
  stat:
    path: "{{ install_prefix }}"
  register: check_install_root

- name: Create install root
  become: "{{ is_admin }}"
  file:
    path: "{{ install_prefix }}"
    mode: 0777
    owner: "{{ ansible_user_id }}"
    recurse: false
    state: directory
  when: not check_install_root.stat.exists

- name: Download and extract tarball
  unarchive:
    src: "{{ release_url }}/v{{ hfst_version }}/{{ hfst_tarball }}"
    dest: "{{ compile_dir }}"
    creates: "{{ hfst_compile_dir }}/configure.ac"
    remote_src: yes

- name: Fix xglib bug in configure
  lineinfile:
    regexp: ^:\)| +\[AC_SUBST\(\[GLIB_CFLAGS\]\)\]\)$
    line: ':)'
    dest: "{{ hfst_compile_dir }}/configure.ac"

- name: Running ./autoreconf -i 
  command: "autoreconf -i"
  args:
    chdir: "{{ hfst_compile_dir }}"
    creates: libtool

# Setting prefix explicitly to be able to replace it later in scripts
- name: Running ./configure 
  command: "./configure --enable-all-tools --with-readline --enable-fsmbook-tests --prefix=/usr/local"
  args:
    chdir: "{{ hfst_compile_dir }}"
    creates: config.log

- name: Set gcc module call
  set_fact:
    gcc_modcall: "{{ 'module load gcc/5.4.0 &&' if env_csc_hpc is defined else '' }}"
    
- name: Running make 
  shell: bash --login -c "{{ gcc_modcall }} make -j8 > MAKE.log"
  args:
    chdir: "{{ hfst_compile_dir }}"
    #creates: MAKE.log
    
- name: Running make check 
  shell: bash --login -c "{{ gcc_modcall }} make check  > MAKE_CHECK.log"
  args:
    chdir: "{{ hfst_compile_dir }}"
    #creates: MAKE_CHECK.log

- name: Fix missing "bin" dir bug in Makefile
  become: no
  file:
    path: "{{ hfst_install_dir }}/bin"
    mode: 0775
    recurse: no
    state: directory

- name: Set python module call
  set_fact:
    python_modcall: "{{ 'module load swig && module load {{ python3_module }} &&' if env_csc_hpc is defined else '' }}"

- name: Running make install
  shell: "make install prefix={{ hfst_install_dir }} > MAKE_INSTALL.log"
  args:
    chdir: "{{ hfst_compile_dir }}"
    creates: "{{ hfst_install_dir }}/bin/hfst-lookup"

- name: Building python module
  shell: bash --login -c  "{{ python_modcall }}python3 setup.py build_ext --inplace --local-hfst"
  args:
    chdir: "{{ hfst_compile_dir }}/python"

- name: Installing python module
  shell: bash --login -c  "{{ python_modcall }}python3 setup.py install --prefix={{ hfst_install_dir }} "
  args:
    chdir: "{{ hfst_compile_dir }}/python"

- name: Checking python module
  shell: bash --login -c  "./test.sh --python python3 --pythonpath {{ hfst_install_dir }}/lib/python{{ python3_base_version }}/site-packages"
  args:
    chdir: "{{ hfst_compile_dir }}/python/test"
  environment:
    LD_LIBRARY_PATH: "{{ hfst_install_dir }}/lib/:{{ ansible_env.LD_LIBRARY_PATH }}"
  when: false # disable for now

# This is a workaround to be able to compile everything just once
# And install to multiple places

- name: Fix permissions (if shared group is set)
  file:
    path={{ hfst_install_dir }}
    group={{ shared_group }}
    mode="g+rwX,o+rX"
    recurse=yes
  when: shared_group is defined