- name: Install packages required for hfst
  yum: name={{ item }} state=present
  with_items:
  - gcc
  - gcc-c++
  - readline-devel
  - python-pip
  - python-devel
  - swig

- name: Install python dependencies using pip
  pip:
    name: hfst
    state: present

- name: Create tmpdirs hfst
  file:
    path: "{{ hfst_tmp }}/{{ item.0 }}"
    state: directory
    mode: 0755
  with_nested:
   - "{{ hfst_components }}"

- name: Get hfst packages
  get_url:
    url: "{{ hfst_url }}/{{ item.0 }}.deb"
    dest: "{{ hfst_tmp }}/{{ item.0 }}"
    checksum: "{{ item.1 }}"
    mode: a+x
  with_nested:
   - "{{ hfst_components }}"

- name: Extract packages
  command: ar x {{ item.0 }}.deb
  args:
    chdir: "{{ hfst_tmp }}/{{ item.0 }}"
  with_nested:
   - "{{ hfst_components }}"

- name: Extract files
  unarchive:
    src: "{{ hfst_tmp }}/{{ item.0 }}/data.tar.xz"
    dest: "{{ hfst_tmp }}/{{ item.0 }}"
    remote_src: yes
  with_nested:
   - "{{ hfst_components }}"

- name: copy binaries
  command: bash -c "tar cf - . | tar xf - -C /usr/local/bin"
  args:
    chdir: "{{ hfst_tmp }}/{{ hfst_bin }}/usr/bin/"

- name: copy library
  command: bash -c "tar cf - . | tar xf - -C /usr/local/lib"
  args:
    chdir: "{{ hfst_tmp }}/{{ hfst_lib }}/usr/lib/x86_64-linux-gnu/"

- name: add /usr/local/lib
  copy:
    src: locallib.conf
    dest: /etc/ld.so.conf.d/locallib.conf
    mode: 0644

- name: "ldconfig: register new path"
  command: ldconfig -v
