webdomain_sanat: sanat.csc.fi
webaliases_sanat: []
webdomain_nimiarkisto: nimiarkisto.fi
webaliases_nimiarkisto: []


apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"
ssl_params_sanat:
  certificate_file: "/etc/pki/tls/certs/{{ webdomain_sanat }}.crt"
  certificate_key_file: "/etc/pki/tls/private/{{ webdomain_sanat }}.key"
ssl_params_nimiarkisto:
  certificate_file: "/etc/pki/tls/certs/{{ webdomain_nimiarkisto }}.crt"
  certificate_key_file: "/etc/pki/tls/private/{{ webdomain_nimiarkisto }}.key"


hfst_tmp: /tmp/hfst
hfst_url: http://apertium.projectjj.com/apt/release/pool/main/h/hfst/
hfst_bin: hfst_3.12.2~r3289-0ubuntu1~trusty1_amd64
hfst_lib: libhfst49_3.12.2~r3289-0ubuntu1~trusty1_amd64
hfst_components:
 - [ '{{ hfst_bin }}' , 'sha256:3b97482d4836975d0edf38daf670d9289310a6f0e5d6a605c9129433bf16cf5d' ]
 - [ '{{ hfst_lib }}' , 'sha256:9c462762f8af66712a15bd88953df0a1f24e852b93da7cd3e4a751fb30e4421b' ]


hhvm_port: 9000
memcached_memory_limit: 4G
composer_keep_updated: true

nodejs_version: "7.10.0"

php_enable_php_fpm: true
sms_xml:
  wiki_username: "SyncBot"
  wiki_password: "SyncBot12"
  debug: "True"
