- hosts: web
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: hfst
      tags: hfst
    - role: hhvm
      tags: hhvm
    - role: advertine.nodejs
      tags: nodejs
    - role: geerlingguy.composer
    - role: geerlingguy.memcached
    - role: apache_ssl
      tags: apache
    - role: geerlingguy.apache
      tags: apache
    - role: mediawiki
      tags: mediawiki
    - role: smsxml
      tags: smsxml
    - role: selinux
    - role: geerlingguy.repo-epel
    - role: firewall
      tags: firewall

  tasks:
    - name: Install admin tools
      yum: name={{ item }} state=present
      with_items:
        - nano
        - htop
