- hosts: db
  become: yes
  roles:
    - role: wikidb
      tags: db

- hosts: web
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: hfst
      tags: hfst
    - role: php
      tags: php
    - role: advertine.nodejs
      tags: nodejs
    - role: geerlingguy.composer
    - role: geerlingguy.memcached
      tags: memcached
    - role: apache_ssl
      tags: apache
    - role: geerlingguy.apache
      tags: apache
    #- role: elastic.elasticsearch
      #tags: elasticsearch
      #es_instance_name: wikis
      #es_heap_size: 4G
    - role: mediawiki
      tags: mediawiki
    - role: smsxml
      tags: smsxml
    - role: selinux
    - role: firewall
      tags: firewall

- hosts: all
  become: yes
  tasks:
    - name: Install admin tools
      yum: name={{ item }} state=present
      with_items:
        - nano
        - htop
        - mytop
