---

- name: Ensure directories exists
  become: no
  command: mkdir -p "{{ item }}"
  args:
    creates: "{{ item }}"
    warn: false
  loop:
    - "{{ src_root }}"
    - "{{ install_dir }}/bin"

- name: Get source
  git:
    repo: "{{ release_url }}/{{ item.name }}"
    dest: "{{ src_root }}/{{ item.name }}"
    version: "{{ item.githash }}"
    accept_hostkey: yes
  loop: "{{ git_pkgs  }}"


- name: Set gcc module call
  set_fact:
    gcc_modcall: "{{ 'module load 9.1.0 &&' if env_csc_hpc is defined else '' }}"
    
- name: Running make 
  shell: bash --login -c "{{ gcc_modcall }} make  > MAKE.log"
  args:
    chdir: "{{ src_root }}/cstlemma/src"
  

- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX"
    recurse: yes
  when: shared_group is defined