---
# defaults

package_name: finnish-parse
release_url: https://github.com/TurkuNLP/Finnish-dep-parser.git
version: "{{ finnish_parse_version }}"
compile_dir: "{{ compile_root }}/Finnish-dep-parser/{{ branch }}"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"