
- name: Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tagtools_install_dir }}"
    - "{{ tagtools_compile_dir }}"
    
- name: Unpack from tar
  unarchive:
    src: "{{ tagtools_tar}}"
    dest: "{{ tagtools_compile_dir }}"
    remote_src: yes

- name: Fix permissions (if shared group is set)
  file:
    path="{{ tagtools_install_dir }}/.."
    group={{ shared_group }}
    mode="g+rwX,o+rX"
    recurse=yes
  when: shared_group is defined
