---
# defaults

package_name: sparv_pipeline
version: "{{ sparv_pipeline_version }}"
file_basename: "{{ package_name }}_{{ sparv_pipeline_version }}"
release_url: "https://spraakbanken.gu.se/pub/sparv.dist/sparv_pipeline/{{ file_basename }}.zip"

src_root: "{{ compile_root }}"
compile_dir: "{{ src_root }}/{{ file_basename }}"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"