---
# tasks file for Pytorch

- name: Clone Pytorch
  git:
    repo:  "{{ release_url }}"
    dest: "{{ compile_root }}/pytorch/"
    remote: upstream
    version: "{{ pytorch_version.githash }}"


- name: Make Tools
  shell: "module load {{ python3_module }} && python3 setup.py install"
  args:
    chdir: "{{ compile_root }}/pytorch"

- name: Fix permissions (again)
  file:
    path="{{ install_dir }}/.."
    group=csc
    mode="g+rwX,o+rX"
    recurse=yes



