---
# tasks file for Kaldi

- name: Clone Kaldi
  git:
    repo:  "{{ release_url }}"
    dest: "{{ compile_root }}/pytorch/"
    remote: upstream
    version: "{{ kaldi_version.githash }}"


- name: Make Tools
  shell: "module load python-env/3.5.3 && python3 setup.py install"
  args:
    chdir: "{{ compile_root }}/pytorch"
    creates: MAKE_TOOLS.log

- name: Fix permissions (again)
  file:
    path="{{ install_dir }}/.."
    group=csc
    mode="g+rwX,o+rX"
    recurse=yes



